/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminSignupRouteImport } from './routes/admin-signup'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MureedRouteImport } from './routes/mureed'
import { Route as MureedLoginRouteImport } from './routes/mureed-login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupAccountRouteImport } from './routes/setup-account'
import { Route as SubAdminLoginRouteImport } from './routes/sub-admin-login'
import { Route as SubAdminSignupRouteImport } from './routes/sub-admin-signup'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin-login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminPeerRouteImport } from './routes/admin.peer'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as MureedIndexRouteImport } from './routes/mureed.index'
import { Route as MureedDashboardRouteImport } from './routes/mureed.dashboard'
import { Route as MureedMyInformationRouteImport } from './routes/mureed.my-information'
import { Route as AdminMureedsIndexRouteImport } from './routes/admin.mureeds.index'
import { Route as AdminMureedsAddRouteImport } from './routes/admin.mureeds.add'
import { Route as AdminMureedsIdIndexRouteImport } from './routes/admin.mureeds.$id.index'
import { Route as AdminMureedsIdEditRouteImport } from './routes/admin.mureeds.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin-signup',
  path: '/admin-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MureedRoute = MureedRouteImport.update({
  id: '/mureed',
  path: '/mureed',
  getParentRoute: () => rootRouteImport,
} as any)
const MureedLoginRoute = MureedLoginRouteImport.update({
  id: '/mureed-login',
  path: '/mureed-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAccountRoute = SetupAccountRouteImport.update({
  id: '/setup-account',
  path: '/setup-account',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAdminLoginRoute = SubAdminLoginRouteImport.update({
  id: '/sub-admin-login',
  path: '/sub-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAdminSignupRoute = SubAdminSignupRouteImport.update({
  id: '/sub-admin-signup',
  path: '/sub-admin-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin-login',
  path: '/super-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeerRoute = AdminPeerRouteImport.update({
  id: '/peer',
  path: '/peer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const MureedIndexRoute = MureedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MureedRoute,
} as any)
const MureedDashboardRoute = MureedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MureedRoute,
} as any)
const MureedMyInformationRoute = MureedMyInformationRouteImport.update({
  id: '/my-information',
  path: '/my-information',
  getParentRoute: () => MureedRoute,
} as any)
const AdminMureedsIndexRoute = AdminMureedsIndexRouteImport.update({
  id: '/mureeds/',
  path: '/mureeds/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMureedsAddRoute = AdminMureedsAddRouteImport.update({
  id: '/mureeds/add',
  path: '/mureeds/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMureedsIdIndexRoute = AdminMureedsIdIndexRouteImport.update({
  id: '/mureeds/$id/',
  path: '/mureeds/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMureedsIdEditRoute = AdminMureedsIdEditRouteImport.update({
  id: '/mureeds/$id/edit',
  path: '/mureeds/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/admin-signup': typeof AdminSignupRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mureed': typeof MureedRouteWithChildren
  '/mureed-login': typeof MureedLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-account': typeof SetupAccountRoute
  '/sub-admin-login': typeof SubAdminLoginRoute
  '/sub-admin-signup': typeof SubAdminSignupRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/peer': typeof AdminPeerRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mureed/dashboard': typeof MureedDashboardRoute
  '/mureed/my-information': typeof MureedMyInformationRoute
  '/admin/': typeof AdminIndexRoute
  '/mureed/': typeof MureedIndexRoute
  '/admin/mureeds/add': typeof AdminMureedsAddRoute
  '/admin/mureeds/': typeof AdminMureedsIndexRoute
  '/admin/mureeds/$id/edit': typeof AdminMureedsIdEditRoute
  '/admin/mureeds/$id/': typeof AdminMureedsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-signup': typeof AdminSignupRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mureed-login': typeof MureedLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-account': typeof SetupAccountRoute
  '/sub-admin-login': typeof SubAdminLoginRoute
  '/sub-admin-signup': typeof SubAdminSignupRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/peer': typeof AdminPeerRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mureed/dashboard': typeof MureedDashboardRoute
  '/mureed/my-information': typeof MureedMyInformationRoute
  '/admin': typeof AdminIndexRoute
  '/mureed': typeof MureedIndexRoute
  '/admin/mureeds/add': typeof AdminMureedsAddRoute
  '/admin/mureeds': typeof AdminMureedsIndexRoute
  '/admin/mureeds/$id/edit': typeof AdminMureedsIdEditRoute
  '/admin/mureeds/$id': typeof AdminMureedsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/admin-signup': typeof AdminSignupRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mureed': typeof MureedRouteWithChildren
  '/mureed-login': typeof MureedLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-account': typeof SetupAccountRoute
  '/sub-admin-login': typeof SubAdminLoginRoute
  '/sub-admin-signup': typeof SubAdminSignupRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/peer': typeof AdminPeerRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mureed/dashboard': typeof MureedDashboardRoute
  '/mureed/my-information': typeof MureedMyInformationRoute
  '/admin/': typeof AdminIndexRoute
  '/mureed/': typeof MureedIndexRoute
  '/admin/mureeds/add': typeof AdminMureedsAddRoute
  '/admin/mureeds/': typeof AdminMureedsIndexRoute
  '/admin/mureeds/$id/edit': typeof AdminMureedsIdEditRoute
  '/admin/mureeds/$id/': typeof AdminMureedsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/admin-signup'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/mureed'
    | '/mureed-login'
    | '/reset-password'
    | '/setup-account'
    | '/sub-admin-login'
    | '/sub-admin-signup'
    | '/super-admin-login'
    | '/admin/dashboard'
    | '/admin/peer'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/mureed/dashboard'
    | '/mureed/my-information'
    | '/admin/'
    | '/mureed/'
    | '/admin/mureeds/add'
    | '/admin/mureeds/'
    | '/admin/mureeds/$id/edit'
    | '/admin/mureeds/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/admin-signup'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/mureed-login'
    | '/reset-password'
    | '/setup-account'
    | '/sub-admin-login'
    | '/sub-admin-signup'
    | '/super-admin-login'
    | '/admin/dashboard'
    | '/admin/peer'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/mureed/dashboard'
    | '/mureed/my-information'
    | '/admin'
    | '/mureed'
    | '/admin/mureeds/add'
    | '/admin/mureeds'
    | '/admin/mureeds/$id/edit'
    | '/admin/mureeds/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/admin-signup'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/mureed'
    | '/mureed-login'
    | '/reset-password'
    | '/setup-account'
    | '/sub-admin-login'
    | '/sub-admin-signup'
    | '/super-admin-login'
    | '/admin/dashboard'
    | '/admin/peer'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/mureed/dashboard'
    | '/mureed/my-information'
    | '/admin/'
    | '/mureed/'
    | '/admin/mureeds/add'
    | '/admin/mureeds/'
    | '/admin/mureeds/$id/edit'
    | '/admin/mureeds/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSignupRoute: typeof AdminSignupRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MureedRoute: typeof MureedRouteWithChildren
  MureedLoginRoute: typeof MureedLoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupAccountRoute: typeof SetupAccountRoute
  SubAdminLoginRoute: typeof SubAdminLoginRoute
  SubAdminSignupRoute: typeof SubAdminSignupRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-signup': {
      id: '/admin-signup'
      path: '/admin-signup'
      fullPath: '/admin-signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mureed': {
      id: '/mureed'
      path: '/mureed'
      fullPath: '/mureed'
      preLoaderRoute: typeof MureedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mureed-login': {
      id: '/mureed-login'
      path: '/mureed-login'
      fullPath: '/mureed-login'
      preLoaderRoute: typeof MureedLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-account': {
      id: '/setup-account'
      path: '/setup-account'
      fullPath: '/setup-account'
      preLoaderRoute: typeof SetupAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-admin-login': {
      id: '/sub-admin-login'
      path: '/sub-admin-login'
      fullPath: '/sub-admin-login'
      preLoaderRoute: typeof SubAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-admin-signup': {
      id: '/sub-admin-signup'
      path: '/sub-admin-signup'
      fullPath: '/sub-admin-signup'
      preLoaderRoute: typeof SubAdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin-login': {
      id: '/super-admin-login'
      path: '/super-admin-login'
      fullPath: '/super-admin-login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/peer': {
      id: '/admin/peer'
      path: '/peer'
      fullPath: '/admin/peer'
      preLoaderRoute: typeof AdminPeerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mureed/': {
      id: '/mureed/'
      path: '/'
      fullPath: '/mureed/'
      preLoaderRoute: typeof MureedIndexRouteImport
      parentRoute: typeof MureedRoute
    }
    '/mureed/dashboard': {
      id: '/mureed/dashboard'
      path: '/dashboard'
      fullPath: '/mureed/dashboard'
      preLoaderRoute: typeof MureedDashboardRouteImport
      parentRoute: typeof MureedRoute
    }
    '/mureed/my-information': {
      id: '/mureed/my-information'
      path: '/my-information'
      fullPath: '/mureed/my-information'
      preLoaderRoute: typeof MureedMyInformationRouteImport
      parentRoute: typeof MureedRoute
    }
    '/admin/mureeds/': {
      id: '/admin/mureeds/'
      path: '/mureeds'
      fullPath: '/admin/mureeds/'
      preLoaderRoute: typeof AdminMureedsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mureeds/add': {
      id: '/admin/mureeds/add'
      path: '/mureeds/add'
      fullPath: '/admin/mureeds/add'
      preLoaderRoute: typeof AdminMureedsAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mureeds/$id/': {
      id: '/admin/mureeds/$id/'
      path: '/mureeds/$id'
      fullPath: '/admin/mureeds/$id/'
      preLoaderRoute: typeof AdminMureedsIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mureeds/$id/edit': {
      id: '/admin/mureeds/$id/edit'
      path: '/mureeds/$id/edit'
      fullPath: '/admin/mureeds/$id/edit'
      preLoaderRoute: typeof AdminMureedsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPeerRoute: typeof AdminPeerRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMureedsAddRoute: typeof AdminMureedsAddRoute
  AdminMureedsIndexRoute: typeof AdminMureedsIndexRoute
  AdminMureedsIdEditRoute: typeof AdminMureedsIdEditRoute
  AdminMureedsIdIndexRoute: typeof AdminMureedsIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPeerRoute: AdminPeerRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMureedsAddRoute: AdminMureedsAddRoute,
  AdminMureedsIndexRoute: AdminMureedsIndexRoute,
  AdminMureedsIdEditRoute: AdminMureedsIdEditRoute,
  AdminMureedsIdIndexRoute: AdminMureedsIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MureedRouteChildren {
  MureedDashboardRoute: typeof MureedDashboardRoute
  MureedMyInformationRoute: typeof MureedMyInformationRoute
  MureedIndexRoute: typeof MureedIndexRoute
}

const MureedRouteChildren: MureedRouteChildren = {
  MureedDashboardRoute: MureedDashboardRoute,
  MureedMyInformationRoute: MureedMyInformationRoute,
  MureedIndexRoute: MureedIndexRoute,
}

const MureedRouteWithChildren =
  MureedRoute._addFileChildren(MureedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminSignupRoute: AdminSignupRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MureedRoute: MureedRouteWithChildren,
  MureedLoginRoute: MureedLoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupAccountRoute: SetupAccountRoute,
  SubAdminLoginRoute: SubAdminLoginRoute,
  SubAdminSignupRoute: SubAdminSignupRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
